// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AAffix: typeof import("@arco-design/web-vue")["Affix"];
    ABreadcrumb: typeof import("@arco-design/web-vue")["Breadcrumb"];
    ABreadcrumbItem: typeof import("@arco-design/web-vue")["BreadcrumbItem"];
    AButton: typeof import("@arco-design/web-vue")["Button"];
    ACard: typeof import("@arco-design/web-vue")["Card"];
    ACardGrid: typeof import("@arco-design/web-vue")["CardGrid"];
    ACol: typeof import("@arco-design/web-vue")["Col"];
    AConfigProvider: typeof import("@arco-design/web-vue")["ConfigProvider"];
    ADivider: typeof import("@arco-design/web-vue")["Divider"];
    ADoption: typeof import("@arco-design/web-vue")["Doption"];
    ADropdown: typeof import("@arco-design/web-vue")["Dropdown"];
    AForm: typeof import("@arco-design/web-vue")["Form"];
    AFormItem: typeof import("@arco-design/web-vue")["FormItem"];
    AInput: typeof import("@arco-design/web-vue")["Input"];
    ALayout: typeof import("@arco-design/web-vue")["Layout"];
    ALayoutContent: typeof import("@arco-design/web-vue")["LayoutContent"];
    ALayoutFooter: typeof import("@arco-design/web-vue")["LayoutFooter"];
    ALayoutHeader: typeof import("@arco-design/web-vue")["LayoutHeader"];
    ALayoutSider: typeof import("@arco-design/web-vue")["LayoutSider"];
    AMenu: typeof import("@arco-design/web-vue")["Menu"];
    AMenuItem: typeof import("@arco-design/web-vue")["MenuItem"];
    APageHeader: typeof import("@arco-design/web-vue")["PageHeader"];
    APopover: typeof import("@arco-design/web-vue")["Popover"];
    ARangePicker: typeof import("@arco-design/web-vue")["RangePicker"];
    ARow: typeof import("@arco-design/web-vue")["Row"];
    AScrollbar: typeof import("@arco-design/web-vue")["Scrollbar"];
    ASkeleton: typeof import("@arco-design/web-vue")["Skeleton"];
    ASkeletonLine: typeof import("@arco-design/web-vue")["SkeletonLine"];
    ASpace: typeof import("@arco-design/web-vue")["Space"];
    ASubMenu: typeof import("@arco-design/web-vue")["SubMenu"];
    ATypographyText: typeof import("@arco-design/web-vue")["TypographyText"];
    IconApps: typeof import("@arco-design/web-vue/es/icon")["IconApps"];
    IconClose: typeof import("@arco-design/web-vue/es/icon")["IconClose"];
    IconHome: typeof import("@arco-design/web-vue/es/icon")["IconHome"];
    IconLayout: typeof import("@arco-design/web-vue/es/icon")["IconLayout"];
    IconPoweroff: typeof import("@arco-design/web-vue/es/icon")["IconPoweroff"];
    IconQuestionCircle: typeof import("@arco-design/web-vue/es/icon")["IconQuestionCircle"];
    IconQuote: typeof import("@arco-design/web-vue/es/icon")["IconQuote"];
    IconUser: typeof import("@arco-design/web-vue/es/icon")["IconUser"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
